language: python
python:
  - 2.7
  - 3.6
dist: trusty
cache: pip

addons:
  apt:
    packages:
      # For validating C/C++ style
      - vera++
      # For validating XML
      - libxml2-utils
      # For building C code
      - libc6:i386
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi

before_install:
  # Work around ludicrous Travis bug
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support
  - python support/travis_blocking_stdout.py
  # Bring pip up to date 
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy,matplotlib numpy scipy matplotlib
  # SpiNNakerManchester internal dependencies; development mode
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNUtils.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNMachine.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNStorageHandlers.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNMan.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/PACMAN.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/DataSpecification.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/spalloc.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNFrontEndCommon.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/sPyNNaker.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/sPyNNaker8.git
  # C dependencies
  - support/gitclone.sh https://github.com/SpiNNakerManchester/spinnaker_tools.git
  - support/gitclone.sh https://github.com/SpiNNakerManchester/spinn_common.git
  - support/gitclone.sh https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon.git
  - support/gitclone.sh https://github.com/SpiNNakerManchester/sPyNNaker.git
  - export SPINN_DIRS=$PWD/spinnaker_tools
  - export NEURAL_MODELLING_DIRS=$PWD/sPyNNaker/neural_modelling

install:
  - pip install -r requirements-test.txt
  - python ./setup.py install
  # Initialise builds against spinnaker_tools
  - make -C $SPINN_DIRS
  - make -C spinn_common install
  - make -C SpiNNFrontEndCommon/c_common install

before_script:
  # Make a test config
  - echo '[Machine]' > ~/.spynnaker.cfg
  - echo "machineName = $SPINNAKER_BOARD_ADDRESS" >> ~/.spynnaker.cfg
  - echo "version = ${SPINNAKER_BOARD_VERSION:-5}" >> ~/.spynnaker.cfg
  - echo '[Database]' >> ~/.spynnaker.cfg
  - echo '[Simulation]' >> ~/.spynnaker.cfg
  - echo '[Buffers]' >> ~/.spynnaker.cfg

script:
  # Python
  ### Disabled as not currently any tests
  # - py.test unittests
  - flake8 examples python_models8
  ### Disabled as not currently any tests
  # - flake8 unittests
  # XML
  - find python_models8 -name '*.xml' | xargs -r -n 1 support/validate-xml.sh
  # C 
  - make -C c_models
  - support/run-vera.sh c_models/src
  # Documentation build tests would go here
